### PR TITLE
fix performance related issue where multiple connections results in exponential amounts of work

### PR DESCRIPTION
**Pull request by jezell**

### CODE REVIEW

**Comment by Ni55aN** [comment]
If it is still relevant for someone, the [v1.4.5-rc.1](https://www.npmjs.com/package/rete/v/1.4.5-rc.1) contains this fix. Additional tests are needed with the rete-task-plugin plugin, rete-module-plugin, etc.

**Comment by JannikGM** [comment]
Has this landed in the final 1.4.5? Should this be closed?

**Comment by ChBernat** [comment]
@Ni55aN This is a fairly pressing problem for my project currently. Any chance we can get that merged soon?

**Comment by Ni55aN** [comment]
[1.4.6-rc.1](https://www.npmjs.com/package/rete/v/1.4.6-rc.1) contains this fix

cc @ChBernat

**Pull request merged**
